# $ docker run -it --rm d7xdev/pipx:alpine

FROM alpine:latest
LABEL maintainer="d7xdev"

## Note: `pipx` requires Bash
RUN apk add --no-cache --update \
        python3 \
        py3-pip \
        bash \
    && rm -rf ~/.cache/* /usr/local/share/man /tmp/*                                               

WORKDIR /scratch

RUN python3 -m pip install --user pipx

RUN python3 -m pipx ensurepath

CMD ["/bin/bash"]
